### ISSUE TITLE
Migrate Sales Data

### ISSUE THREAD

**Issue by derdeakon** [ubertheme/magento2_data_migration#12]
Hi,

 i have a problem with the Sales Data. In my current Shiop i have 51 Orders. This orders will be shown in step 7 with all other options.

![migrate datat](https://cloud.githubusercontent.com/assets/7261600/11436949/b890eb38-94e9-11e5-930c-9cc7502c4eb2.PNG)

After i have imported the Order, it will only 2 Orders imported.

Also i see no items i have ordered in my magento 2

![success](https://cloud.githubusercontent.com/assets/7261600/11437205/17ff8082-94ec-11e5-9706-f7f8b3e3b9c4.PNG)

Do you know why .

**Comment by quienti** [comment]
See here : https://github.com/ubertheme/magento2_data_migration/issues/11

**Comment by derdeakon** [comment]
It works for the orders great: 

But i have a problem to see the items in the order. Is there any possiblity to show these items ?

![items](https://cloud.githubusercontent.com/assets/7261600/11437601/598dbc50-94ef-11e5-955c-d7ee2096aaf8.PNG)

**Comment by quynhvv** [comment]
@derdeakon: Let's try reset this step and re-start data migration on this step.

And tell me know how it goes.
Regards,
quynhvv

**Comment by derdeakon** [comment]
I tried this sometimes, but there is always the same result.

**Comment by quynhvv** [comment]
@derdeakon:
I have detected the root of issue as you said. 
That because Magento 2 have change way to save the data with field named 'weee_tax_applied'
So, to solve the issue let's do steps:

Step 1: Make manual reset the step 7 by URL: http://URL_TO_THIS_TOOL/migrate/reset/step/7
Step 2: 
Open the file at: `/protected/controllers/MigrateController.php`
and file to the block code:

```
 //sales_order_item
                                    $models = Mage1SalesOrderItem::model()->findAll("order_id = {$sales_order->entity_id}");
                                    if ($models){
                                        foreach ($models as $model){
                                            $model2 = new Mage2SalesOrderItem();
                                            foreach ($model2->attributes as $key => $value){
                                                if (isset($model->$key)){
                                                    $model2->$key = $model->$key;
                                                }
                                            }
                                            $model2->store_id = MigrateSteps::getMage2StoreId($model->store_id);
                                            $model2->save();
                                        }
                                    }
```

and replace it by block code:

```
//sales_order_item
                                    $models = Mage1SalesOrderItem::model()->findAll("order_id = {$sales_order->entity_id}");
                                    if ($models){
                                        foreach ($models as $model){
                                            $model2 = new Mage2SalesOrderItem();
                                            foreach ($model2->attributes as $key => $value){
                                                if (isset($model->$key)){
                                                    $val = $model->$key;
                                                    /**
                                                     * Because Magento2 was change method to save weee_tax_applied to database:
                                                     * So we have to make convert this
                                                     */
                                                    if ($key == 'weee_tax_applied'){
                                                        $val = json_encode(unserialize($val));
                                                    }
                                                    $model2->$key = $val;
                                                }
                                            }
                                            $model2->store_id = MigrateSteps::getMage2StoreId($model->store_id);
                                            $model2->save();
                                        }
                                    }
```

and re-start data migration on this step.

Do it and tell me know how it goes. 
Regards,
quynhvv.

**Comment by derdeakon** [comment]
Hi quynhvv,

your fix works fine for me. Thanks

**Comment by dswtpvtltd** [comment]
I have notice that It is not migrating the custom options , tier prices and group prices.

**Comment by UberthemeTeam** [comment]
Hi @vidyasagar4679 ,

Our migration script here at Github was based on an outdated source code with limited feature sets which we no longer maintain. We replaced with a newer UB Data Migration Pro version [here](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro). 

Our Pro version helps you migrate tier prices smoothly. M2 discarded group prices, thus our migration tool automatically converts group prices into tier prices in M2 after migration. 

At present, our Pro version supports core and custom attributes for Product. For customers, we support core system attributes only, the custom fields for sales data are not handled yet. This is partially because such custom fields do not exist in default Magento 2. Further, for those added manually or via third-party extensions, it would be best to leave such custom fields handled by the associated extensions, instead of separately migrating those. 

Hope that helps.

Regards,
Ubertheme team

**Comment by dswtpvtltd** [comment]
Thank you very much to reply me. I am freelancer and most of clients has max budget is $500 to migrate his site. If I will pay you $399 then what may I earn in this?

**Comment by dswtpvtltd** [comment]
but it is not problem. you have developed and give the effort to create this tool then you will be liable to earn whatever you invested in developing this tool.

**Comment by UberthemeTeam** [comment]
Hi @vidyasagar4679 , 

For any additional question, you can reach us anytime via our email info (at) ubertheme.com. 
You can check out alternatives to find a migration tool that fits you most. 

Based on many completed projects, we are confident that our migration tool will definitely save you pretty much time. 

Regards,
Ubertheme team
