### ISSUE TITLE
Issue on Shipping Method lenght 

### ISSUE THREAD

**Issue by quienti** [ubertheme/magento2_data_migration#14]
Hello, i want to migrate my magento 1.9 to magento 2.0 but at step 7 i got an error 
![captureshi](https://cloud.githubusercontent.com/assets/7326954/11473551/500611f6-9773-11e5-9f7d-31bcfe82a125.PNG)

Is it possible to fix this error? 

On my old magento is used Owebia-Shipping to manage shipping 

Edit: i cut all my string to 32 but i don't understand why magento 2 doesn't accept more. Because in the database field is set in 'varchar(255)'

Thank you

**Comment by quienti** [comment]
I got an another error message at the end of the seventh step.

![capturextoo](https://cloud.githubusercontent.com/assets/7326954/11478759/19244222-978f-11e5-9b4f-8a9ccbd42ab7.PNG)

**Comment by quynhvv** [comment]
@quienti :
I have detected the root of issues as you said, that because Magento 2 have some changed of max length in some fields: shipping_method, store_name and 'shipping_method' ...
I have tuning to handle this and committed to this repository.
To solve the issue, let's update below files to your working:

 `https://github.com/ubertheme/magento2_data_migration/blob/master/protected/controllers/MigrateController.php`

`https://github.com/ubertheme/magento2_data_migration/blob/master/protected/data/step7_reset.sql`

`https://github.com/ubertheme/magento2_data_migration/blob/master/protected/models/db/mage2/Mage2SalesOrderPaymentPeer.php`

`https://github.com/ubertheme/magento2_data_migration/blob/master/protected/models/db/mage2/Mage2SalesOrderPeer.php`

`https://github.com/ubertheme/magento2_data_migration/blob/master/protected/models/db/mage2/Mage2SalesQuoteAddressPeer.php`

and make reset the step 7 after your changing.

and re-start data migration on this step.

Regards,
quynhvv

**Comment by quienti** [comment]
Ok, thanks, I wiil try again

**Comment by quienti** [comment]
Now all order are imported but it is impossible to enter in order, an exception appears 

![execpt](https://cloud.githubusercontent.com/assets/7326954/11500186/cc4f250a-982b-11e5-8916-50e49a481a33.PNG)

http://pastebin.com/n5G4uHhM

certain order works and i think it is one that had a field name too large (>32 chars) before, while those who field was < 32 chars doesn't work now

**Comment by quynhvv** [comment]
@quienti:

> i think it is one that had a field name too large (>32 chars) before, while those who field was < 32 chars doesn't work now

=> The issue as screenshot doesn't related to field name as you think.
Did you make write permission for folders, files as Magento required:
http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html

Did you clean the Magento 2 cache? and delete some needed files:

`find var/* -type f -or -type d | grep -v 'session' | xargs rm -rf && \
rm -rf pub/static/*`

At the end, did you try reset all steps and re-start migration on latest source of this tool?

Regards,
quynhvv

**Comment by quienti** [comment]
Yes, I have clean the Magento 2 cache and I tried 3 times all migration with your last master today

**Comment by quynhvv** [comment]
@channel: 
I would like to announcement that, we have just released one Magento 2 modules for this at:

https://github.com/ubertheme/module-ubdatamigration

Regards,
quynhvv
