### ISSUE TITLE
Application runtime path is not valid

### ISSUE THREAD

**Issue by diomededavid** [ubertheme/magento2_data_migration#8]
I am unable to run the script i get an error that the Application runtime path is not valid. Screenshot attached. my permissions on the entire files and folders for that script are 777
![firefox_screenshot_2015-11-22t19-21-30 247z](https://cloud.githubusercontent.com/assets/14153189/11325771/c7bebc86-9113-11e5-8101-d49e9b86e694.png)

**Comment by diomededavid** [comment]
Update. I added a runtime folder to the /protected/ folder, which seems to be missing. That removed the Application runtime path error above. A new error has shown up. CDbConnection failed to open the DB connection: could not find driver. Screenshot attached.
![firefox_screenshot_2015-11-22t22-40-46 163z](https://cloud.githubusercontent.com/assets/14153189/11326767/6b462a0e-912f-11e5-8029-d3c076ed7f5f.png)

**Comment by quynhvv** [comment]
Hi diomededavid,

About "runtime" folder, let's follow the guide of Migrate tool at
https://github.com/ubertheme/magento2_data_migration/blob/master/README.md

About: CDbConnection failed to open the DB connection
=>That because you miss sqlite in your web server. The tool was using the
sqllite, so you have to enable sqlite in your web server.
To enable the SQLite, let's follow this article:
http://serverfault.com/questions/32982/how-do-i-enable-sqlite-on-linux-apache-php

Regards,
quynhvv

On Mon, Nov 23, 2015 at 5:41 AM, diomededavid notifications@github.com
wrote:

> Update. I added a runtime folder to the /protected/ folder, which seems to
> be missing. That removed the Application runtime path error above. A new
> error has shown up. CDbConnection failed to open the DB connection: could
> not find driver. Screenshot attached.
> [image: firefox_screenshot_2015-11-22t22-40-46 163z]
> https://cloud.githubusercontent.com/assets/14153189/11326767/6b462a0e-912f-11e5-8029-d3c076ed7f5f.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/8#issuecomment-158815263
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002
